# Generated by Django 2.0.4 on 2018-04-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Comment',
            field=models.ManyToManyField(related_name='Comment', to='blog.Comment'),
        ),
    ]
